[]{
;1
@<SystemProperty.cg<-NUL-<
@<SystemProperty.File.100<-NUL-<
@<Settings.7L.ini<-NUL-<
;2
@<.\FXXF7l\SystemProperty.cg<-NUL-<
@<.\FXXF7l\SystemProperty.File.100<-NUL-<
@<.\FXXF7l\Settings.7L.ini<-NUL-<
;3
@<.\SystemProperty.cg<-NUL-<
@<.\SystemProperty.File.100<-NUL-<
@<.\Settings.7L.ini<-NUL-<
}
