[]{
@<SystemProperty.cg<-NUL-<
@<SystemProperty.7L<-NUL-<
@<Settings.7L.ini<-NUL-<
@<.\FXXF7l.7z.gz\FXXF7l.7z\SystemProperty.cg<-NUL-<
@<.\FXXF7l.7z.gz\FXXF7l.7z\SystemProperty.7L<-NUL-<
@<.\FXXF7l.7z.gz\FXXF7l.7z\Settings.7L.ini<-NUL-<
@<.\Settings.7L.ini<-NUL-<
}
